services:
  frontend-app:
    build:
      context: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
     - network

  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./bd:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=catalog_4432
      - POSTGRES_USER=catalog_user
      - POSTGRES_DB=catalog
    networks:
     - network

  spring-boot-app:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
    container_name: catalog-backend
    depends_on: 
      - postgresdb
    networks:
     - network


volumes:
  node_modules:

networks:
  network: