services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
     - network

  postgres:
    image: postgres:latest
    restart: no
    ports:
      - 5432:5432
    volumes:
      - ./bd:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=catalog_4432
      - POSTGRES_USER=catalog_user
      - POSTGRES_DB=catalog

  spring-boot-app:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - '8080:8080'
    depends_on:
      - postgres


volumes:
  node_modules:

networks:
  network: